#!/bin/sh
SolutionDir="../../"

solution=`${SolutionDir}cflags $1`
project="-std=c++14 -fPIC -fvisibility=hidden"
project="$project
-Dimgui_EXPORTS
-DIMGUI_USER_CONFIG=\"imgui_config.h\"
-I${SolutionDir}include
-Idear_bindings_generated
-Idear_bindings_generated/backends
-Iimgui
-Iimgui/backends
"
libsdl3=`pkg-config --cflags sdl3`
echo $solution $project $libsdl3
