#!/bin/sh
SolutionDir="../../"

cflags() {
	solution=`${SolutionDir}get --cflags $1`
	project="-std=c++14 -fPIC -fvisibility=hidden"
	project="$project
	-Dimgui_EXPORTS
	-DIMGUI_USER_CONFIG=\"imgui_config.h\"
	-I${SolutionDir}include
	-Idear_bindings_generated
	-Idear_bindings_generated/backends
	-Iimgui
	-Iimgui/backends
	"
	libsdl3=`pkg-config --cflags sdl3`
	echo $solution $project $libsdl3
}
ldflags() {
	solution=`${SolutionDir}get --ldflags $1`
	project="-Wl,-Bsymbolic"
	echo $solution $project
}
case $1 in
	--cflags) cflags $2 ;;
	--ldflags) ldflags $2 ;;
	*) echo "Usage $0 (--cflags|--ldflags) (Release|Debug)" >&2 ;;
esac

