#!/bin/sh
solution="-ggdb3 -O0"
case $(uname -s) in
	Linux)      lto="-flto=auto" ;;
	Darwin)     lto="-flto=auto" ;;
	Windows_NT) lto="" ;;
	*)          echo "Unknown platform" >&2
esac
echo $solution # $lto (is very slow)
