#!/bin/sh
cflags() {
	case "$1" in
		Debug)          solution="-ggdb3 -O0 -D_DEBUG" ;;
		Release)        solution="-g -O2 -DNDEBUG" ;;
		# removed RelWithDebInfo, we always can strip debug symbols after build
		*) echo "Bad BUILD_TYPE, should be Debug or Release" >&2; exit 1 ;;
	esac
	#case $(uname -s) in
	#	Linux)      lto="-flto=auto" ;;
	#	Darwin)     lto="-flto=auto" ;;
	#	Windows_NT) lto="" ;;
	#	*)          echo "Unknown platform" >&2
	#esac
	echo $solution # $lto (is very slow)
}
ldflags() {
	solution=""
	echo $solution
}
name() {
	grep "define APP_METADATA_NAME_STRING" include/metadata.h | cut -d'"' -f2
}
prettyos() {
	case $(uname -s) in
		Linux)      os="Linux" ;;
		Darwin)     os="MacOS" ;;
		Windows_NT) os="Windows" ;;
		*)          echo "Unknown platform" >&2
	esac
	echo $os
}
version() {
	grep "define APP_VERSION_STR" include/metadata.h | cut -d'"' -f2
}
case $1 in
	--cflags) cflags $2 ;;
	--ldflags) ldflags $2 ;;
	--name) name $2 ;;
	--prettyos) prettyos $2 ;;
	--version) version $2 ;;
	*) echo "Usage $0 (--cflags|--ldflags|--prettyos|--name|--version) (Release|Debug)" >&2 ;;
esac

