#!/bin/sh
cflags() {
	case "$1" in
		RelWithDebInfo) solution="-g -O2 -DNDEBUG" ;;
		Release)        solution="-O2 -DNDEBUG" ;;
		Debug)          solution="-ggdb3 -O0 -D_DEBUG" ;;
		*) echo "Bad BUILD_TYPE, should be RelWithDebInfo|Release|Debug" >&2; exit 1 ;;
	esac
	#case $(uname -s) in
	#	Linux)      lto="-flto=auto" ;;
	#	Darwin)     lto="-flto=auto" ;;
	#	Windows_NT) lto="" ;;
	#	*)          echo "Unknown platform" >&2
	#esac
	echo $solution # $lto (is very slow)
}
ldflags() {
	solution=""
	echo $solution
}
case $1 in
	--cflags) cflags $2 ;;
	--ldflags) ldflags $2 ;;
	*) echo "Usage $0 (--cflags|--ldflags) (Release|RelWithDebInfo|Debug)" >&2 ;;
esac

