#!/bin/sh
sdl=`pkg-config --libs sdl3`
app="
-I../../../third-party/static/ui/dear_bindings_generated
-I../../../third-party/static/ui/imgui
-I../../../third-party/static/ui/dear_bindings_generated/backends
-I../../../third-party/static/ui/imgui/backends
-I../../../third-party/static/ecs/flecs
-I../../../include
"
echo -std=c11 -fPIC -fvisibility=hidden $app $sdl
