#!/bin/sh
SolutionDir="../../../"
ProjectDir="`dirname $0`/"

solution=`${SolutionDir}ldflags`
soname=`${ProjectDir}soname`
project="-Wl,-Bsymbolic -Wl,-Bsymbolic -Wl,--default-symver -Wl,-soname,$soname -shared"
case $(uname -s) in
	Linux)      libdcimgui="-L${SolutionDir}third-party/static/ui" ;;
	Darwin)     libdcimgui="-L${SolutionDir}third-party/static/ui -L/usr/local/lib -L/opt/local/lib" ;;
	Windows_NT) libdcimgui="-L${SolutionDir}third-party/static/ui" ;;
	*)          echo "Unknown platform" >&2
esac
echo $solution $project $libdcimgui
