#!/bin/sh
name="$(basename $(realpath ..))"
suffix=
# Suffix may be used to have a -debug or versionning, not decided yet. It will implies globbing in mod-host.c
case $(uname -s) in
	Linux)      echo "$name$suffix.so" ;;
	Darwin)     echo "$name$suffix.dylib" ;;
	Windows_NT) echo "$name$suffix.dll" ;;
	*)          echo "Unknown platform" >&2
esac
