#!/bin/sh
name="$(basename $(realpath ..))"
ver=1
case $(uname -s) in
	Linux)      echo "$name.so.$ver" ;;
	Darwin)     echo "$name-$ver.dylib" ;;
	Windows_NT) echo "$name-$ver.dll" ;;
	*)          echo "Unknown platform" >&2
esac
