#!/bin/sh
SolutionDir="../../"

cflags() {
	solution=`${SolutionDir}get --cflags $1`
	project="-std=gnu99 -Iflecs -Dflecs_EXPORTS"
	echo $solution $project
}
case $1 in
	--cflags) cflags $2 ;;
	*) echo "Usage $0 --cflags (Release|RelWithDebInfo|Debug)" >&2 ;;
esac

