#!/bin/sh
SolutionDir="../../../"
ProjectDir="`dirname $0`/"

solution=`${SolutionDir}ldflags`
soname=`${ProjectDir}soname`
project="-Wl,--default-symver -Wl,-soname,$soname -shared -Wl,-rpath=.:.. -Wl,-Bsymbolic"
echo $solution $project
