#!/bin/sh
SolutionDir="../../../"
ProjectDir="`dirname $0`/"

solution=`${SolutionDir}ldflags $1`
soname=`${ProjectDir}soname $1`
project="-Wl,--default-symver -Wl,-soname,$soname -shared"
case $(uname -s) in
	Linux)      dynload="-Wl,-rpath=.:.. -Wl,-Bsymbolic" ;;
	Darwin)     dynload="-Wl,-rpath=.:.. -Wl,-Bsymbolic" ;;
	Windows_NT) dynload="" ;;
	*)          echo "Unknown platform" >&2
esac
echo $solution $project $dynload
