#!/bin/sh
SolutionDir="../"

cflags() {
	solution=`${SolutionDir}get --cflags $1`
	project="-Wall -Wformat -std=c11 -fvisibility=hidden"
	project="$project
	-I${SolutionDir}lib/ui/dear_bindings_generated
	-I${SolutionDir}lib/ui/imgui
	-I${SolutionDir}lib/ui/dear_bindings_generated/backends
	-I${SolutionDir}lib/ui/imgui/backends
	-I${SolutionDir}lib/ecs/flecs
	-I${SolutionDir}include
	"
	libsdl3=`pkg-config --cflags sdl3`
	echo $solution $project $libsdl3
}
ldflags() {
	ODIR=x64/$1

	solution=`${SolutionDir}get --ldflags $1`
	case $(uname -s) in
		Linux)      project="-Wl,-rpath=.:.. -Wl,--export-dynamic -Wl,-Bsymbolic" ;;
		Darwin)     project="-Wl,-rpath=.:.. -Wl,--export-dynamic -Wl,-Bsymbolic" ;;
		Windows_NT) project="" ;;
		*)          echo "Unknown platform" >&2
	esac
	case $(uname -s) in
		Linux)      libdcimgui="-L${SolutionDir}lib/ui/${ODIR}" ;;
		Darwin)     libdcimgui="-L${SolutionDir}lib/ui/${ODIR} -L/usr/local/lib -L/opt/local/lib" ;;
		Windows_NT) libdcimgui="-L${SolutionDir}lib/ui/${ODIR}" ;;
		*)          echo "Unknown platform" >&2
	esac
	echo $solution $project $libdcimgui
}
ldlibs() {
	sdl=`pkg-config --libs sdl3`
	os=""
	flecs=""
	case $(uname -s) in
		Linux)      imgui="-ldcimgui -lm -lstdc++";;
		Darwin)     imgui="-framework ApplicationServices -framework Cocoa -framework IOKit -framework CoreVideo -ldcimgui" ;;
		Windows_NT) flecs="-lwsock32 -lws2_32"; imgui="-lgdi32 -limm32 -ldcimgui -lstdc++" ; os="-ldbghelp" ;;
		*)          echo "Unknown platform" >&2
	esac
	echo $flecs $imgui $sdl $os
}
exename() {
	name="llss"
	ext=""
	case $(uname -s) in
		Windows_NT) ext=".exe" ;;
	esac
	echo $name$ext
}
case $1 in
	--cflags) cflags $2 ;;
	--ldflags) ldflags $2 ;;
	--ldlibs) ldlibs $2 ;;
	--exename) exename $2 ;;
	*) echo "Usage $0 (--cflags|--ldflags|--ldlibs|--exename) (Release|Debug)" >&2 ;;
esac

