#!/bin/sh
SolutionDir="../../../"

solution=`${SolutionDir}cflags`
project="-Wall -Wformat -std=gnu99 -fvisibility=hidden"
project="$project
-I${SolutionDir}lib/ui/dear_bindings_generated
-I${SolutionDir}lib/ui/imgui
-I${SolutionDir}lib/ui/dear_bindings_generated/backends
-I${SolutionDir}lib/ui/imgui/backends
-I${SolutionDir}lib/ecs/flecs
-I${SolutionDir}include
"
libsdl3=`pkg-config --cflags sdl3`
echo -fPIC -fvisibility=hidden $project $libsdl3
