#!/bin/sh
SolutionDir="../"

solution=`${SolutionDir}cflags`
project="-Wall -Wformat -std=c11 -fvisibility=hidden"
project="$project
-I${SolutionDir}third-party/static/ui/dear_bindings_generated
-I${SolutionDir}third-party/static/ui/imgui
-I${SolutionDir}third-party/static/ui/dear_bindings_generated/backends
-I${SolutionDir}third-party/static/ui/imgui/backends
-I${SolutionDir}third-party/static/ecs/flecs
-I${SolutionDir}include
"
libsdl3=`pkg-config --libs sdl3`
echo $solution $project $libsdl3
