#!/bin/bash
#TODO Both GNU ld and LLVM lld take --export-dynamic flag
#TODO ld that ships with OS X takes -export_dynamic flag
declare -a LDFLAGS=(
-Wl,--export-dynamic
-L ../third-party/static/ui
)
echo ${LDFLAGS[*]}
