#!/bin/sh
SolutionDir="../"

solution=`${SolutionDir}ldflags`
case $(uname -s) in
	Linux)      project="-Wl,-rpath=.:.. -Wl,--export-dynamic -Wl,-Bsymbolic" ;;
	Darwin)     project="-Wl,-rpath=.:.. -Wl,--export-dynamic -Wl,-Bsymbolic" ;;
	Windows_NT) project="" ;;
	*)          echo "Unknown platform" >&2
esac
case $(uname -s) in
	Linux)      libdcimgui="-L${SolutionDir}lib/ui" ;;
	Darwin)     libdcimgui="-L${SolutionDir}lib/ui -L/usr/local/lib -L/opt/local/lib" ;;
	Windows_NT) libdcimgui="-L${SolutionDir}lib/ui" ;;
	*)          echo "Unknown platform" >&2
esac
echo $solution $project $libdcimgui
