#!/bin/sh
case $(uname -s) in
	Linux)      echo "-Wl,-Bsymbolic -L../third-party/static/ui" ;;
	Darwin)     echo "-Wl,-Bsymbolic -L../third-party/static/ui -L/usr/local/lib -L/opt/local/lib" ;;
	Windows_NT) echo "-Wl,-Bsymbolic -L../third-party/static/ui" ;;
	*)          echo "Unknown platform" >&2
esac
