#!/bin/sh
sdl=`pkg-config --libs sdl3`
case $(uname -s) in
	Linux)      imgui="-ldcimgui -lm -lstdc++";;
	Darwin)     imgui="-framework ApplicationServices -framework Cocoa -framework IOKit -framework CoreVideo -ldcimgui" ;;
	Windows_NT) imgui="-lgdi32 -limm32 -ldcimgui" ;;
	*)          echo "Unknown platform" >&2
esac
echo $imgui $sdl
