#!/bin/sh
sdl=`pkg-config --libs sdl3`
imgui="-ldcimgui -lm -lstdc++"
case $(uname -s) in
	Linux)      echo "-ldcimgui -lm -lstdc++ -ldl $sdl" ;;
	Darwin)     echo "-framework ApplicationServices -framework Cocoa -framework IOKit -framework CoreVideo -ldcimgui $sdl" ;;
	Windows_NT) echo "-lgdi32 -limm32 -ldcimgui $sdl" ;;
	*)          echo "Unknown platform" >&2
esac
